### ISSUE TITLE
problem with SQLAlchemyJobStore

### ISSUE THREAD

**Issue by pcace** [okainov/ebay-kleinanzeigen#10]
Hi there, i am trying to get this to run in docker but fail with this error message: 

```
2023-02-05T11:18:47.247461163Z Traceback (most recent call last):
2023-02-05T11:18:47.247519985Z File "/app/main.py", line 16, in <module>
2023-02-05T11:18:47.247533795Z 'default': SQLAlchemyJobStore(url='sqlite:///jobs.sqlite')
2023-02-05T11:18:47.247540306Z File "/usr/local/lib/python3.8/site-packages/apscheduler/jobstores/sqlalchemy.py", line 60, in __init__
2023-02-05T11:18:47.247549996Z Column('id', Unicode(191, _warn_on_bytestring=False), primary_key=True),
2023-02-05T11:18:47.247553986Z File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 325, in __init__
2023-02-05T11:18:47.247558106Z super().__init__(length=length, **kwargs)
2023-02-05T11:18:47.247561356Z TypeError: __init__() got an unexpected keyword argument '_warn_on_bytestring'
```

any idea where i would need to look to solve this problem?

thanks a lot!

**Comment by okainov** [comment]
Hmmm, looks odd, I'll take a look, thanks for the report!

**Comment by D4Ci0** [comment]
Same error here

**Comment by D4Ci0** [comment]
@okainov Is there any chance for you having some time fixing the 'bug'? Would really appreciate the bugfix, worked like a charm before.
